name: CI

on:
  - pull_request

jobs:
  job1:
    runs-on: ubuntu-latest
    name: build-and-deploy
    steps:

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
       

      - name: Build and test
        working-directory: ProgDistOuarda
        run: |
          export SHELL=/bin/bash
          ./gradlew build

      - name: Build Docker image
        working-directory: ProgDistOuarda
        run: |
          docker build -t rental-service:latest .

      - name: Show docker images
        run: |
          docker images